ERROR: React.PropTypes deprecated
React.PropTypes is deprecated as of React v15.5.
Use the prop-types library.

Error Closed.
"Cannot read property 'string' of undefined | React.PropTypes"